Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory '/home/rosselio/djangoproj/static' in the STATICFILES_DIRS setting does not exist.

System check identified 1 issue (0 silenced).
[23/Apr/2024 11:58:14] "GET / HTTP/1.1" 200 182
Not Found: /favicon.ico
[23/Apr/2024 11:58:14] "GET /favicon.ico HTTP/1.1" 404 2269
[23/Apr/2024 11:59:52] "GET / HTTP/1.1" 200 182
[2024-04-23 20:20:59 +0800] [17654] [INFO] Starting gunicorn 22.0.0
[2024-04-23 20:20:59 +0800] [17654] [INFO] Listening at: http://127.0.0.1:8000 (17654)
[2024-04-23 20:20:59 +0800] [17654] [INFO] Using worker: sync
[2024-04-23 20:20:59 +0800] [17655] [INFO] Booting worker with pid: 17655
[2024-04-23 20:21:32 +0800] [17654] [CRITICAL] WORKER TIMEOUT (pid:17655)
[2024-04-23 12:21:32 +0000] [17655] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/rosselio/djangoproj/djangoproj_env10/lib/python3.10/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-04-23 12:21:32 +0000] [17655] [INFO] Worker exiting (pid: 17655)
[2024-04-23 20:21:32 +0800] [17792] [INFO] Booting worker with pid: 17792
[2024-04-23 12:37:52 +0000] [17792] [INFO] Worker exiting (pid: 17792)
[2024-04-23 20:37:52 +0800] [17654] [INFO] Handling signal: term
[2024-04-23 20:37:52 +0800] [17654] [INFO] Shutting down: Master
!!!
!!! WARNING: configuration file should have a valid Python extension.
!!!

[2024-04-27 09:55:53 +0800] [30896] [INFO] Starting gunicorn 22.0.0
[2024-04-27 09:55:53 +0800] [30896] [INFO] Listening at: http://0.0.0.0:5000 (30896)
[2024-04-27 09:55:53 +0800] [30896] [INFO] Using worker: sync
[2024-04-27 09:55:53 +0800] [30897] [INFO] Booting worker with pid: 30897
[2024-04-27 09:55:53 +0800] [30897] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runserver'
[2024-04-27 09:55:53 +0800] [30897] [INFO] Worker exiting (pid: 30897)
[2024-04-27 09:55:53 +0800] [30898] [INFO] Booting worker with pid: 30898
[2024-04-27 09:55:53 +0800] [30898] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vs7182/.local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runserver'
[2024-04-27 09:55:54 +0800] [30898] [INFO] Worker exiting (pid: 30898)
[2024-04-27 09:55:54 +0800] [30896] [ERROR] Worker (pid:30897) exited with code 3
[2024-04-27 09:55:54 +0800] [30896] [ERROR] Worker (pid:30898) was sent SIGTERM!
[2024-04-27 09:55:54 +0800] [30896] [ERROR] Shutting down: Master
[2024-04-27 09:55:54 +0800] [30896] [ERROR] Reason: Worker failed to boot.
